### ISSUE TITLE
是否支持UI框架？

### ISSUE THREAD

**Issue by beixue1990** [endday/formily-vue#1]
不好意思，没有其他的联系方法，在此处联系您，想询问一下formily-vue现在是否支持其他UI框架如element或iview？
期待您的回复。本人联系方式，微信beixuebeixue。

**Comment by endday** [comment]
不支持的，根据源码的结构来看，formily分为核心库和ui层，这个应该是vue的核心支持库，ui是不包括在内的。
建议你去官方issue看看，我这个也只是fork了别人的代码试着跑起来而已。
我在issue提问过，官方说vue的支持正在做，不知道现在什么进度了。

**Comment by beixue1990** [comment]
非常感谢。
